FROM node:18-alpine

# Crear directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto del servidor de desarrollo de React
EXPOSE 3000

# Comando para iniciar el servidor de desarrollo
CMD ["npm", "start"]