services:
  # Backend 
  backend:
    container_name: backend_gymautoma_app
    image: backend_gymautoma_image
    build:
      context: ./backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
    ports:
      - '127.0.0.1:5000:5000'
    environment:
      - DEBUG=${APP_DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    networks:
      - gymautoma

  # Frontend 
  frontend:
    container_name: frontend_gymautoma_app
    image: frontend_gymautoma_image
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:5005/api
    networks:
      - gymautoma

  # Base de datos PostgreSQL
  db:
    container_name: db_gymautoma_app
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gymautoma
      
  # # FastAPI app (modelo + API)
  # fastapi:
  #   container_name: fastapi_gymautoma_app
  #   build:
  #     context: ./fastapi-app
  #   image: docker-gymautoma-fastapi
  #   environment:
  #     - OLLAMA_SERVER_URL=http://ollama:11434
  #   ports:
  #     - "5005:5005"
  #   depends_on:
  #     - ollama
  #   networks:
  #     - gymautoma

    

volumes:
  db_data:

networks:
  gymautoma:
    driver: bridge
