# Generated by Django 5.2.7 on 2025-10-21 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_config', '0002_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('peso_corporal_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duracion_minutos', models.IntegerField()),
                ('calorias_quemadas', models.IntegerField(default=0)),
                ('nivel_intensidad', models.IntegerField(help_text='Nivel de intensidad del 1 al 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('completado', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='training.entrenamientos')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='profile_config.perfil')),
            ],
            options={
                'verbose_name_plural': 'Progresión',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('personalizado', 'Personalizado')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('entrenamientos_completados', models.IntegerField(default=0)),
                ('calorias_totales_quemadas', models.IntegerField(default=0)),
                ('peso_inicial_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_final_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='profile_config.perfil')),
            ],
            options={
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
