# Generated by Django 5.2.7 on 2025-10-21 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasEjercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías de Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('disponible_en_casa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Equipamiento',
            },
        ),
        migrations.CreateModel(
            name='GruposMusculares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('region_corporal', models.CharField(choices=[('superior', 'Tren Superior'), ('inferior', 'Tren Inferior'), ('core', 'Core/Abdomen'), ('total', 'Cuerpo Completo')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Grupos Musculares',
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('gif', 'GIF')], max_length=20)),
                ('archivo', models.FileField(upload_to='ejercicios/')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=1)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Multimedia',
                'ordering': ['ejercicio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('instrucciones', models.TextField(help_text='Paso a paso del ejercicio')),
                ('nivel_dificultad', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('calorias_estimadas', models.IntegerField(default=0, help_text='Calorías quemadas por repetición/minuto')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios', to='exercises.categoriasejercicios')),
            ],
            options={
                'verbose_name_plural': 'Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='EjerciciosEquipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_obligatorio', models.BooleanField(default=True, help_text='Si es False, es equipamiento opcional/alternativo')),
                ('cantidad', models.IntegerField(default=1, help_text='Cantidad de este equipamiento necesario')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.ejercicios')),
            ],
            options={
                'verbose_name_plural': 'Ejercicios - Equipamiento',
            },
        ),
        migrations.CreateModel(
            name='EjerciciosGruposMusculares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_enfoque', models.CharField(choices=[('primario', 'Primario'), ('secundario', 'Secundario')], max_length=20)),
                ('porcentaje_activacion', models.IntegerField(default=50, help_text='Porcentaje de activación muscular', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.ejercicios')),
            ],
            options={
                'verbose_name_plural': 'Ejercicios - Grupos Musculares',
            },
        ),
        migrations.CreateModel(
            name='EntrenamientosEjercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1)),
                ('series', models.IntegerField(default=3)),
                ('repeticiones', models.IntegerField(default=10)),
                ('peso_recomendado_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tiempo_descanso_segundos', models.IntegerField(default=60)),
                ('notas', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.ejercicios')),
            ],
            options={
                'verbose_name_plural': 'Entrenamientos - Ejercicios',
                'ordering': ['entrenamiento', 'orden'],
            },
        ),
    ]
