# Generated by Django 5.2.7 on 2025-10-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamientosejercicios',
            name='entrenamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.entrenamientos'),
        ),
        migrations.AddField(
            model_name='ejerciciosequipamiento',
            name='equipamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.equipamiento'),
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='equipamiento',
            field=models.ManyToManyField(related_name='ejercicios', through='exercises.EjerciciosEquipamiento', to='exercises.equipamiento'),
        ),
        migrations.AddField(
            model_name='ejerciciosgruposmusculares',
            name='grupo_muscular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.gruposmusculares'),
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='grupos_musculares',
            field=models.ManyToManyField(related_name='ejercicios', through='exercises.EjerciciosGruposMusculares', to='exercises.gruposmusculares'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='exercises.ejercicios'),
        ),
        migrations.AlterUniqueTogether(
            name='entrenamientosejercicios',
            unique_together={('entrenamiento', 'ejercicio')},
        ),
        migrations.AlterUniqueTogether(
            name='ejerciciosequipamiento',
            unique_together={('ejercicio', 'equipamiento')},
        ),
        migrations.AlterUniqueTogether(
            name='ejerciciosgruposmusculares',
            unique_together={('ejercicio', 'grupo_muscular')},
        ),
    ]
