# Generated by Django 5.2.7 on 2025-10-21 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        ('profile_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('fuerza', 'Fuerza'), ('hipertrofia', 'Hipertrofia'), ('resistencia', 'Resistencia'), ('funcional', 'Funcional'), ('cardio', 'Cardio'), ('mixto', 'Mixto')], max_length=50)),
                ('duracion_semanas', models.IntegerField()),
                ('dias_semana', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Rutinas',
            },
        ),
        migrations.CreateModel(
            name='Entrenamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('dia_semana', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('duracion_estimada_minutos', models.IntegerField()),
                ('orden', models.IntegerField(default=1)),
                ('ejercicios', models.ManyToManyField(related_name='entrenamientos', through='exercises.EntrenamientosEjercicios', to='exercises.ejercicios')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to='training.rutina')),
            ],
            options={
                'verbose_name_plural': 'Entrenamientos',
                'ordering': ['rutina', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='LesionesEntrenamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraindicacion', models.TextField(help_text='Descripción de por qué esta lesión afecta este entrenamiento')),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('prohibido', 'Prohibido')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.entrenamientos')),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_config.lesionesrestricciones')),
            ],
            options={
                'verbose_name_plural': 'Lesiones - Entrenamientos',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.IntegerField()),
                ('repeticiones_objetivo', models.IntegerField()),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tiempo_descanso_segundos', models.IntegerField(default=60)),
                ('notas', models.TextField(blank=True)),
                ('completada', models.BooleanField(default=False)),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='training.entrenamientos')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['entrenamiento', 'numero_serie'],
            },
        ),
    ]
