# Generated by Django 5.2.7 on 2025-10-21 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('unidad_peso', models.CharField(choices=[('kg', 'Kilogramos'), ('lb', 'Libras')], default='kg', max_length=10)),
                ('unidad_distancia', models.CharField(choices=[('km', 'Kilómetros'), ('mi', 'Millas')], default='km', max_length=10)),
                ('notificaciones_activas', models.BooleanField(default=True)),
                ('tema_oscuro', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Configuraciones de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel', models.IntegerField(default=1, help_text='1=Bien, 5=Excesivamente fatigado', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='LesionesRestricciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('grupo_muscular_afectado', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_recuperacion_estimada', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('nivel_gravedad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Lesiones y Restricciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Objetivos',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20)),
                ('altura', models.DecimalField(decimal_places=2, help_text='Altura en cm', max_digits=5)),
                ('peso_actual', models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='PerfilEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_muscular', models.CharField(help_text='Ej: Bíceps, Hombros, Piernas', max_length=100)),
                ('nivel_fatiga', models.CharField(choices=[('bien', 'Bien'), ('poco_fatigado', 'Poco fatigado'), ('fatigado', 'Fatigado'), ('muy_fatigado', 'Muy fatigado'), ('excesivamente_fatigado', 'Excesivamente fatigado')], max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Perfil Estados',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
