# Generated by Django 5.2.7 on 2025-10-21 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_config', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesionesrestricciones',
            name='entrenamientos_afectados',
            field=models.ManyToManyField(related_name='lesiones', through='training.LesionesEntrenamientos', to='training.entrenamientos'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='objetivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='profile_config.objetivo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rutina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='training.rutina'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesionesrestricciones',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesiones', to='profile_config.perfil'),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='profile_config.perfil'),
        ),
        migrations.AddField(
            model_name='perfilestado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_config.estado'),
        ),
        migrations.AddField(
            model_name='perfilestado',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_config.perfil'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estados',
            field=models.ManyToManyField(related_name='perfiles', through='profile_config.PerfilEstado', to='profile_config.estado'),
        ),
    ]
