# Generated by Django 5.2.7 on 2025-10-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('calorias_objetivo', models.IntegerField(help_text='Calorías diarias objetivo')),
                ('calorias_consumidas', models.IntegerField(default=0)),
                ('proteinas_gramos', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbohidratos_gramos', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grasas_gramos', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('agua_litros', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Nutrición',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlanesNutricionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_dieta', models.CharField(choices=[('definicion', 'Definición'), ('volumen', 'Volumen'), ('mantenimiento', 'Mantenimiento'), ('cetogenica', 'Cetogénica'), ('vegetariana', 'Vegetariana'), ('vegana', 'Vegana')], max_length=50)),
                ('duracion_semanas', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Planes Nutricionales',
            },
        ),
    ]
