# Generated by Django 5.2.7 on 2025-10-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
        ('profile_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricion',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_nutricion', to='profile_config.perfil'),
        ),
        migrations.AddField(
            model_name='planesnutricionales',
            name='nutricion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='nutrition.nutricion'),
        ),
        migrations.AlterUniqueTogether(
            name='nutricion',
            unique_together={('perfil', 'fecha')},
        ),
    ]
